### ISSUE TITLE
Asking for help about the code

### ISSUE THREAD

**Issue by DelinQu** [ljzycmd/BSRSC#2]
Hi [ljzycmd](https://github.com/ljzycmd),

Thanks for your awesome work [Learning Adaptive Warping for Real-World Rolling Shutter Correction](https://openaccess.thecvf.com/content/CVPR2022/papers/Cao_Learning_Adaptive_Warping_for_Real-World_Rolling_Shutter_Correction_CVPR_2022_paper.pdf). Recently I read your paper carefully, but I’m still confused about your implementation, especially about the `Motion Estimation` and `Adaptive Warping` modules. So I would like to ask whether you will consider releasing your code shortly. Or is it possible to get your secret code via [email](mailto:dlqu22@m.fudan.edu.cn)? Thank you so much! :smile:

Delin

**Comment by ljzycmd** [comment]
I have sent an email to you, hope that can help you.

**Comment by DelinQu** [comment]
Oh, so appreciate it!
